/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:caa4622b-f030-4de1-ba76-0a961e769d13",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_0SIlrRlgS",
    "aws_user_pools_web_client_id": "1n8s4gtq07egdhvt6jptvc4l95",
    "oauth": {},
    "aws_user_files_s3_bucket": "cinemabookingfilmimages",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
