name: Cinema Booking CI For Frontend
on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - .github/workflows/react-pipeline.yml
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Packages
        run: npm install
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
      - name: Test
        run: npm run test:coverage
        working-directory: frontend
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_FRONTEND_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_FRONTEND_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-frontend `git subtree split --prefix frontend main`:refs/heads/main --force
