name: Cinema Booking CI For Backend
on:
  push:
    branches:
      - main
    paths:
      - src/**
  pull_request:
    branches:
      - main
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: sneha1234
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        # options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: backend
      - name: Run tests
        run: ./gradlew test
        working-directory: backend
        
      
